image:  docker:19.03.12

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.12-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

before_script:
  - docker login -u groosha -p $USER_TOKEN $CI_REGISTRY

stages:
  - build
#  - push

build-bot:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "tgchat" && $CI_COMMIT_TAG'
  script:
    - |
      docker build \
      -t "$CI_REGISTRY/groosha/$CI_PROJECT_NAME/tgeeksbot:$CI_COMMIT_TAG" .
      docker push $CI_REGISTRY/groosha/$CI_PROJECT_NAME
