image:  docker:19.03.12

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.12-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

before_script:
  - docker login -u $REGISTRY_USERNAME -p $USER_TOKEN $CI_REGISTRY

stages:
  - build


build-tgeeksbot-latest:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "tgchat"'
      when: on_success
  script:
    - |
      docker build --pull -t "$CI_REGISTRY_IMAGE:tgchat_latest" .
      docker push "$CI_REGISTRY_IMAGE:tgchat_latest"


build-tgeeksbot-tagged:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG =~ /tgchat_v\d+.\d+/'
  script:
    - |
      docker pull "$CI_REGISTRY_IMAGE:tgchat_latest"
      docker tag "$CI_REGISTRY_IMAGE:tgchat_latest" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"